version: '3.5'
services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: ./.Docker/php/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/.Docker
      - /var/app/ssl
      - ./.Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
    networks:
      - docker-network
    depends_on:
      - db
  
  #Nginx Service
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - app
    volumes:
      - ./.Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - docker-network
    depends_on:
      - db
      - app

#Docker Networks
networks:
  docker-network:
    name: docker-network
    driver: bridge
